project:
  type: book
  output-dir: docs

book:
  title: "kwapil_2020"
  author: "Seungju Kim"
  date: last-modified
  chapters:
    - index.qmd
    - 01_data_prep.qmd
    - 02_pa_model.qmd
    - 03_ple_model.qmd
    - 04_neg_model.qmd
    - 05_dis_model.qmd
    - 06_negexp_model.qmd

format:
  html:
    theme:
      - cosmo
      - brand




