# Home {.unnumbered}

:::callout-important
All code and data are processed locally on a personal computer. At no time is data stored on GitHub, even temporarily.
:::

This website documents the data preparation and analysis for XXXX.

## How to navigate this website?

1.  To see the raw code files see here.
2.  To view rendered code, simply navigate a chapter on the left panel of this website.
3.  Identify any errors? See below.

## How does this website work?

1.  This data cleaning and analysis is performed locally on a laptop.
2.  Each phase is separated by its own R script file (`.qmd` file)
3.  Thus, each R script *chapter* reflects the actual underlying code used to clean and analyze data. 

> This means that you can also directly suggest edits or corrections **online** (see section below) which will be reflected in the data cleaning workflow.

4.  Everytime the R code is changed or updated, GitHub will track and contain a comment (user must provide) that denotes what changes were made. 

## Spot any errors?
Open an issue in the corresponding chapter you are in. You can find the "*Report an issue*" GitHub button on the **top right** of every page. From there, you can detail what the problem is, and someone will work to resolve the issue. 

## Progress?

You can track current unresolved and resolved issues [here](https://github.com/follhim/sgm_networks_study/issues). 